name: Release Obsidian Plugin

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build plugin
              run: npm run build

            - name: Verify files exist
              run: |
                  [ -f main.js ] || exit 1
                  [ -f manifest.json ] || exit 1
                  [ -f styles.css ] || exit 1

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
