name: Release Obsidian Plugin

on:
    push:
        tags:
            - "*" # triggers on any tag push

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install dependencies & build
              run: |
                  npm install
                  npm run build

            - name: Install GitHub CLI
              run: |
                  sudo apt update
                  sudo apt install gh -y

            - name: Prepare plugin zip
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  zip "zenboard-${tag}.zip" main.js styles.css manifest.json

            - name: Create GitHub release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  gh release create "$tag" \
                    --title "$tag" \
                    --draft \
                    "zenboard-${tag}.zip"
